### ISSUE TITLE
Open ranger half screen

### ISSUE THREAD

**Issue by mrded** [francoiscabrol/ranger.vim#28]
Currently it opens full screen, I believe it will be nice to open it somewhere bellow, so you can still see you working code, and navigate into a new file.

**Comment by francoiscabrol** [comment]
Hi, This is probably not possible with vim (or I have no idea how) but with neovim, it is totally possible. Honestly I don't need this feature since when I want to keep the current file in the tab, I just open a new buffer in a splitted window and then open Ranger in this splitted window (with neovim). It is maybe not the behavour that you are looking for. 

A NerdTree mode for this plugin could be implemented but I am not going to work on it since I don't need it. If someone want to implement it, I can help. I would suggest to create a command like OpenRangerOnTheSide.

**Comment by markus-bauer** [comment]
You could do something like this with simple vim mappings (open a new window, move to it and call Ranger).
 
For example, you can add this to your .vimrc:

```vim
" open ranger here
map <leader>f :Ranger<CR>

" open ranger left
map <leader>fh :lefta  vsp <bar> <C-w>k <bar> :Ranger <CR>

" open ranger right
map <leader>fl :rightb vsp <bar> <C-w>j <bar> :Ranger <CR>

" open ranger 
map <leader>fk :lefta  sp <bar>  <C-w>k <bar> :Ranger <CR>

" open ranger below
map <leader>fj :rightb sp <bar>  <C-w>j <bar> :Ranger <CR>
```

This is not perfect: 
- The new window will be positioned relative to the currently selected window.
- The new file will be opened in the new window. You could map something like this to close the new window and open the last buffer in the previous window:
```vim
" close last window and open last buffer
map <leader>fc <C-w>c <CR> <bar> :blast <CR>
 ```
