### ISSUE TITLE
In neovim (iterm2) ranger doesn't honor vim/terminal colorscheme

### ISSUE THREAD

**Issue by kiyanwang** [francoiscabrol/ranger.vim#30]
When I launch ranger from within `Vim 8` it honours my spacemacs theme (iterm is set to use spacemacs as is vim itself):

![7___no_name__-_vim__vim_](https://user-images.githubusercontent.com/1135464/29556487-e7c4e5d0-871d-11e7-86af-f451b903aacb.png)

When I launch ranger from within `neovim` it doesn't:

![7___no_name__-_nvim__python_](https://user-images.githubusercontent.com/1135464/29556565-21366eba-871e-11e7-80a7-defb08cf0de5.png)

I'm not sure why this is happening :/   Launching ranger from the command line also honors my spacemacs colorscheme.  (both vim/nvim use the same vim config)

**Comment by francoiscabrol** [comment]
The reason why it's because neovim open ranger in its terminal emulator and vim8 just open it in your regular terminal that run your vim instance. So the problem with the color is a problem with the neovim's terminal color and is not related with ranger/ranger.vim specifically. I found this open issue in the neovim's backlog https://github.com/neovim/neovim/issues/4696.

**Comment by kiyanwang** [comment]
@francoiscabrol thank you
