### ISSUE TITLE
Ranger isn't called when opening a directory (neovim)

### ISSUE THREAD

**Issue by CallumHoward** [francoiscabrol/ranger.vim#45]
Hi, I have the following config
```
let g:ranger_replace_netrw = 1          " open ranger when vim open a directory
let g:NERDTreeHijackNetrw = 0
```
however when I do `:e .` or `:e my_dir` I get a new buffer and the status message: `"my_dir" is a directory`.  
When opening vim from the command line with `nvim my_dir`, I get the same thing but it also puts me in insert mode.

I am using neovim v0.2.2, python 2.7.14 and python 3.6.4, `:Checkhealth` is all Ok. Using macOS 10.13.2.

Relevant PR: https://github.com/francoiscabrol/ranger.vim/pull/36

**Comment by francoiscabrol** [comment]
I can reproduce with the command `e .`
but with `nvim my_dir` it works if `my_dir` exists.

**Comment by akrejczinger** [comment]
This is happening for me too. The code in the linked PR didn't solve the issue for me.
nvim v0.2.3-dev
python 3.4.3

**Comment by francoiscabrol** [comment]
Ok so I tried with vim and neovim:
- the command inside vim/neovim `e .` does not work because the feature is implemented to work only with the terminal command `vim .` That should be fix soon but I have to figure out how.
- with vim the feature that allows to open a directory with `vim .` is broken and that should be fix as well. I am going to document that in the readme.
