### ISSUE TITLE
Ranger misaligned columns and rendering problem

### ISSUE THREAD

**Issue by phealeyh** [francoiscabrol/ranger.vim#63]
Hi,

It seems that my ranger is constantly having problems rendering in alignment. This does not happen when I open it up outside of neovim. I will provide a screenshot below:

Ranger within neovim:
![2018-06-11-215018_1280x800_scrot](https://user-images.githubusercontent.com/8462246/41285345-34753436-6e7f-11e8-82d8-2bb760588522.png)

Ranger by itself:
![2018-06-12-202157_1280x800_scrot](https://user-images.githubusercontent.com/8462246/41285337-30c269ee-6e7f-11e8-8469-9b7b2b2d4cb9.png)

The plugin that I am using from you has not been changed at all and I still get the same error when I try to call it without the functions you have created. Thank you!

Versions:
Arch Version: 4.16.13-2
NVIM version: v0.3.0
Ranger Version:  1.9.1
Python Version: 3.6.5
Terminal Emulator: Termite v13

**Comment by enthudave** [comment]
Could you elaborate on what you mean with 'I still get the same error when I try to call it without the functions you have created'
How do you __call__ it?
What functions are you referring to?

**Comment by phealeyh** [comment]
So I basically run :Terminal and then run ranger inside of that terminal and it produces the same results.

**Comment by enthudave** [comment]
If that is the case than obviously this is not a problem with our plugin.
My guess is that you are unaware of the fact that this repo __only__  is a piece of vim script that allows the use of Ranger in (Neo)Vim. When you open a terminal in neovim and then run the ranger command line tool you are at no point using this plugin. So, logic follows that if you have the same issue with and without using this plugin that the problem you experience is not one that can be fixed here.
Either there is an issue with the neovim terminal or [Ranger](https://ranger.github.io), or your system or it's configuration.
I can only venture a guess here because I currently don't have a machine running Arch, but I would recommend you to check if you have the same problem when using a different terminal emulator.
Good luck

**Comment by enthudave** [comment]
Also try a blank ranger configuration, it looks like you have some custom setting, like those dividing lines between columns, I use the default ranger config and I don't have those. I vaguely seem to remember this is one of the things one can customise in ranger. Hence my guess that you have some customisations and that perhaps you will not have the problem with a small change there

**Comment by phealeyh** [comment]
Okay, thank you for your help!
