### ISSUE TITLE
Image Preview

### ISSUE THREAD

**Issue by charlespeters** [francoiscabrol/ranger.vim#9]
in the normal Ranger project there's image previews, is there a way to support that in this vim plugin?

**Comment by francoiscabrol** [comment]
oh this is maybe a neovim's terminal issue. I suppose that it is working in vim and maybe not in neovim because in the case of vim, ranger is opened in the terminal that run vim but with neovim, ranger is opened in the neovim terminal emulator. The behavior can be different... do you use vim or neovim?
